### ISSUE TITLE
Install Problems

### ISSUE THREAD

**Issue by davidbannon** [dosza/LAMWManager-linux#83]
Hello dosza, firstly, overall, looks fantastic !  But ...

I have just tried an install and while the install itself appeared to work fine, I am having some problems with the final product. I have done two things that may have broken your script -
* Install on Debian Bullseye - note you specify U18.04
* Installed in a directory of my choice - I note thats new.
Don't be afraid to tell me to go back and try again with one or the other of the above fixed !

So, while the install proceeded without apparent errrors, when I start the Lazarus it made I note the following -

* Lazarus does not find fpc. Thats strange because I note your script does 'preload' Lazarus up with, eg, the FPC source. So I added the new fpc directory (/home/dbannon/bin/LAMW/lamw4linux/usr/bin) to my path and tried again, same result. So I entered the full path /home/dbannon/bin/LAMW/lamw4linux/usr/bin/fpc, in Lazarus's initial config box, it was happy.
* But now it cannot find fpc.cfg .  So, I copied the one down in ..LAMW tree to my home dir and called it .fpc.cfg - it did appear to be the right file, had extra Android content.
* After that Lazarus opened up nicely but I received a series of errro messages "The package "fclbridgespack" is installed but no valid package file (.lpk) was found. A broken dummy package was created.", .."tfpandroidbridge_pack" ..,  "LazAndroidWizardPack" and so on.
*When I tried to look at Project Options, I get a dialog saying - 
```
Android Wizard: Path Missing!
Path to Android SDK: [ex C:\lamw\sdk]  // yes, I am using the Linux version .....
{Field to enter path} // I entered "/home/dbannon/bin/LAMW/sdk"
```

*  Finally, Project Options looked normal, perhaps, too normal ?   Project Options does not seem to show any Android specific features, the compiler options appears to point -Fi and -Fu to x86-64 things and LCL and GTK2 are defined.  No mention of Android stuff anywhere.  Should there be ?

Sorry, run out of time just now, thought I would get this off to you in case you tell me I MUST use U18.04 or stop messing with destination directory.

Davo

**Comment by dosza** [comment]
First debian 11 is not supported yet,
Everything indicates that the installation is correct,
The error occurred because you did not run lamw4linux from the start menu,
If LAMW4Linux hasn't appeared yet, you can run it with the command startlamw4linux

If the error still persists, you should delete the ~/.lamw4linux folder
and run lamw_manager again so that it restores the settings, but I don't think it's necessary.

**Comment by dosza** [comment]
125 / 5000
Resultados de tradução
You didn't have to do all that, as you've unconfigured the system, the best thing to do is run ./lamw_manager --reset

**Comment by dosza** [comment]
You didn't have to do all that, as you've unconfigured the system, the best thing to do is run ./lamw_manager --reset

**Comment by dosza** [comment]
found the possible (new) error you tried to describe, thanks for reporting this serious bug,
after reset, change the owner of the chosen directory with the command
sudo chown -R your_directory $USER:$USER

**Comment by dosza** [comment]
Has been fixed,
But you need run ./lamw_manager uninstall
After, you need delete any residual directory

**Comment by davidbannon** [comment]
OK dosza, thanks for the quick response.  I did not realise that your script added a menu item, I did not think to look for one, I generally always start Lazarus from a script in ~/bin !  Might be good idea to mention the menu item in the instruction, for old unix die hards like me !

I will uninstall, grab a fresh copy of lamw_manager and try again. 

Will let you know how I go ....

Davo

**Comment by davidbannon** [comment]
Yeah !
A fresh install with "master" and me starting it with the correct menu item, all good !

Thanks dosza.

**Comment by dosza** [comment]
This is already in the bugs section, in the manual https://github.com/dosza/LAMWManager-linux/blob/v0.4.3/lamw_manager/docs/man.md 

In version v0.4.4 it will contain this information in the README.md 
Thanks
