### ISSUE TITLE
Installation script doesn't find jdk

### ISSUE THREAD

**Issue by KatjaD-CH** [dosza/LAMWManager-linux#97]
The installation script doesn't find the Java jdk it has installed seconds before.

```
ERROR: JAVA_HOME is set to an invalid directory: /home/katja/LAMW/jdk/openjdk-11

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

yes: Standardausgabe: Datenübergabe unterbrochen (broken pipe)

ERROR: JAVA_HOME is set to an invalid directory: /home/katja/LAMW/jdk/openjdk-11

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

yes: Standardausgabe: Datenübergabe unterbrochen (broken pipe)
possible network instability! Try later!
```

I've created the environment variable as suggested.
JAVA_HOME=/home/katja/LAMW/jdk/jdk-11.0.15+10/
However it looks like it won't be evaluated by the script.

Additionally I've had the following error messages:
```
jq: error (at <stdin>:33): Cannot index string with string "openjdk_version"
jq: error (at <stdin>:33): Cannot index string with string "security"

```
In the attached file you'll find the complete terminal output including the check of the environment variable.

[lamwinst.log](https://github.com/dosza/LAMWManager-linux/files/8882272/lamwinst.log)

```
katja@MINIBIT:~/Daten/Downloads$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
katja@MINIBIT:~/Daten/Downloads$ uname -a
Linux MINIBIT 5.4.0-117-generic #132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dosza** [comment]
This is a problem with Adoptium API,
Go to /home/katja/LAMW/jdk/
Try this commands:
sudo mv /home/katja/LAMW/jdk/jdk-11.0.15+10 /home/katja/LAMW/jdk/openjdk-11
Re run lamw_manager using

./lamw_manager --reinstall

**Comment by dosza** [comment]
H

**Comment by KatjaD-CH** [comment]
@dosza 
Thank you for the quick response!

```lamw_manager``` doesn't exist. (even after completed installation)
```lamw_manager_setup.sh``` doesn't accept ```--reset```

Therefore I've deleted everything in the LAMW directory and successfully restarted the installation.

Because I'm completely new to cross compilation with FPC/Lazarus I don't know if the following
Problem needs a bug report.

LAMW-Lazarus doesn't link programs out  of the box:
```ld: error: unknown -format value: elf64-x86-64 (supported formats: elf, default, binary)```

**Comment by dosza** [comment]
When you uses  lamw_manager_setup.sh  need additional  --, there docs about this 
Only Linux 64 bit os supported

**Comment by dosza** [comment]
This problem is not related with java,
This is a conflit with ld from ndk-bundle, and has been fixed,
Has been fixed path

Get version v0.5.0 and re-run ```bash lamw_manager_setup.sh```
